// <auto-generated />
namespace COP4834SchoolDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class r9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(r9));
        
        string IMigrationMetadata.Id
        {
            get { return "201603190133304_r9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
