// <auto-generated />
namespace COP4834A02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class R15 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(R15));
        
        string IMigrationMetadata.Id
        {
            get { return "201602190344167_R1.5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
